### ISSUE TITLE
Latest Release 1.725.0 not available on NPM

### ISSUE THREAD

**Issue by drelementzero** [akamai/boomerang#322] opened 2021-04-27 19:50 UTC
Hello can you please publish the 1.725.0 release to NPM?

**Comment by ceckoslab** [comment] 2021-04-28 10:26
Hello @drelementzero 

We are behind schedule with our quarterly open-source backport. I can't promise when we will do the backport and add 1.725.0 to NPM but would version 1.720.0 work for you?

Is there something specific that you are look for in version 1.725.0?

Have a nice day.

**Comment by nicjansma** [comment] 2021-05-22 18:00
Dupe of https://github.com/akamai/boomerang/issues/320

**Closed by nicjansma** 2021-05-22 18:00 UTC
