### ISSUE TITLE
Chrome.loadTimes() is deprecated since Chrome 64

### ISSUE THREAD

**Issue by aaarichter** [akamai/boomerang#227] opened 2018-10-06 19:32 UTC
see https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated

the `navigation` and `continuity` plugins use it

**Comment by nicjansma** [comment] 2018-11-27 15:11
Dupe of https://github.com/akamai/boomerang/issues/182

**Closed by nicjansma** 2018-11-27 15:11 UTC
