### ISSUE TITLE
Performance Audit 2017: Unload Beacon: NavigationTiming unload handler

### ISSUE THREAD

**Issue by nicjansma** [akamai/boomerang#170] opened 2017-12-22 15:48 UTC
The `NavigationTiming` handler is running the main `done` function at `unload`, even if it already ran at `onload`.

We may want to run it again to _just_ populate the `unload` event timestamp, but we probably don't need to re-run all of the code.

![image](https://user-images.githubusercontent.com/1004649/34303939-a3b0725e-e705-11e7-8356-bc0255e3c2bf.png)

**Comment by bluesmoon** [comment] 2017-12-22 16:18
Also consider if page_ready was fired before onload, we won't have all the details from NavTiming.

**Comment by ashenoy2014** [comment] 2019-05-13 23:03
@nicjansma I was able to reproduce this based on our current code base. 
<img width="1075" alt="Screen Shot 2019-05-13 at 3 26 26 PM" src="https://user-images.githubusercontent.com/7560195/57659829-a24dd780-7598-11e9-9ef1-e28d075b197b.png">

But if i switch to the changes from https://github.com/SOASTA/soasta-boomerang/pull/950 , then in the profiler im no longer seeing done() getting called on unload. So looks like PR950 negate the need to address this perf item.

**Comment by ashenoy2014** [comment] 2019-05-17 23:13
Closing this as changes from https://github.com/SOASTA/soasta-boomerang/pull/950 negate the need for this case. Details in previous comment notes.

**Closed** 2019-05-17 23:12 UTC
Labels: performance
